server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    password: dlekgp0912
    port: 15672
    username: dlekgp
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey